AntsAndDoodles.cpp File Reference
#include <iostream>
#include `Tests2.h`
#include `Production.h`
Functions
int main (int argc, const char *argv[])
Function Documentation
main()
int main (int argc, const char * argv[])
The production constructor of the program
Parameters
argc Number of words on the command line
argv[] Array of character strings, the words from the command line
Returns
0 if success
References Tests2::doTests(), Production::getN(), Production::getNumAnts(), Production::getNumDoodlebugs(), Production::getNumTimeSteps(), Production::getPause(), Production::getSeed(), Production::Production(), Production::runProduction(), Production::~Production(), and Tests2::~Tests2().