Doodlebug Class Reference
#include <Doodlebug.h>
Public Member Functions
 Doodlebug ()
 Doodlebug (int r, int c, Grid * grid)
bool move (Grid * grid)
bool breed (Grid * grid)
bool eat (Grid * grid, int r, int c)
void step (Grid * grid)
bool starve ()
virtual ~Doodlebug ()
Protected Attributes
int stepsTilStarve
Constructor & Destructor Documentation
Doodlebug() [1/2]
Doodlebug::Doodlebug ()
Default constructor for a Doodlebug object
References Organism::c, Organism::grid, Organism::movesWithoutBreeding, Organism::r, and stepsTilStarve.
Referenced by breed().
Doodlebug() [2/2]
Doodlebug::Doodlebug (int r, int c, Grid * grid)
Default constructor for a Doodlebug object which has row r and column c
Parameters
r The row of the doodlebug
c The column of the doodlebug
References Organism::c, Grid::getCellOccupant(), Organism::grid, Organism::movesWithoutBreeding, Organism::r, Organism::setAmAnt(), Grid::setCellOccupant(), and stepsTilStarve.
~Doodlebug()
Doodlebug::~Doodlebug () [virtual]
Default destructor method for a Doodlebug Removes the Doodlebug from the board and from its space held in memory
References Organism::c, Organism::grid, Organism::r, and Grid::setCellOccupant().
Referenced by Tests2::doodleDietest().
Member Function Documentation
breed()
bool Doodlebug::breed (Grid * grid) [virtual]
Creates another Doodlebug object. If a Doodlebug survives eight time steps, it will reproduce and create another Doodlebug in an adjacent cell. If no adjacent cells are available, the Doodlebug will wait until the next available turn to create another Doodlebug. If multiple adjacent cells are available, the Doodlebug will choose at random which adjacent cell it will create another Doodlebug.
Returns
whether or not the Doodlebug was created successfully
Implements Organism .
References Organism::c, Organism::canMoveHere(), Doodlebug(), Organism::movesWithoutBreeding, Grid::numDoodlebugs, Organism::r, and Grid::setCellOccupant().
Referenced by Tests2::doodleBreedTest(), Tests2::doodleDontBreedTest(), and step().
eat()
bool Doodlebug::eat (Grid * grid, int r, int c)
Consumes an Ant, moving into its space and removing it from the board
Parameters
grid The home grid for the doodlebug
r The row of the Ant
c The column of the Ant
Returns
Whether or not the Ant was eaten successfully
References Grid::getCellOccupant(), Grid::numAnts, Grid::setCellOccupant(), and stepsTilStarve.
Referenced by Tests2::doodleEatTest(), and move().
move()
bool Doodlebug::move (Grid * grid) [virtual]
Moves the Doodlebug to a nearby cell, usually so that it can eat an Ant If a Doodlebug is adjacent to an Ant (above, below, or to the left or right of the ant), it will move to the Cell of the Ant at random and eat it. If no Ants are nearby, the Doodlebug will move according to the rules of an Ant moving. If the Doodlebug has not eaten any Ants for three time steps, it will die of starvation at the end of the third time step. If no Cells are available, the Doodlebug will remain in the same location.
Returns
Whether the Doodlebug moved successfully
Implements Organism .
References Organism::c, Organism::canMoveHere(), Organism::doodleCanMoveHere(), eat(), Grid::getCellOccupant(), Organism::isPrey(), Organism::movesWithoutBreeding, Grid::n, Organism::r, Grid::setCellOccupant(), and stepsTilStarve.
Referenced by Tests2::doodleDontMoveTest(), Tests2::doodleMoveTest(), and step().
starve()
bool Doodlebug::starve ()
Checks whether the Doodlebug will starve
Returns
true if the Doodlebug starved, false otherwise
References stepsTilStarve.
Referenced by step().
step()
void Doodlebug::step (Grid * grid) [virtual]
Causes the Doodlebug to take a step, i.e. move and/or breed
Implements Organism .
References breed(), move(), Organism::movesWithoutBreeding, Grid::numDoodlebugs, and starve().
Field Documentation
stepsTilStarve
int Doodlebug::stepsTilStarve [protected]
Referenced by Doodlebug(), eat(), move(), and starve().
The documentation for this class was generated from the following files:
 Doodlebug.h
 Doodlebug.cpp