Ant Class Reference
#include <Ant.h>
Public Member Functions
 Ant ()
 Ant (int r, int c, Grid * grid)
bool move (Grid * grid)
bool breed (Grid * grid)
void step (Grid * grid)
 ~Ant ()
Additional Inherited Members
Constructor & Destructor Documentation
Ant() [1/2]
Ant::Ant ()
Default constructor for an Ant object
References Organism::c, Organism::grid, Organism::movesWithoutBreeding, and Organism::r.
Referenced by breed().
Ant() [2/2]
Ant::Ant (int r, int c, Grid * grid)
Constructs an Ant object at a certain location on the grid
Parameters
r The row of the Ant
c the column of the Ant
References Organism::c, Organism::grid, Organism::movesWithoutBreeding, Organism::r, and Grid::setCellOccupant().
~Ant()
Ant::~Ant ()
Destructor for Ant objects Clears memory formerly held by an Ant
References Organism::c, Organism::grid, Organism::r, and Grid::setCellOccupant().
Referenced by Tests2::antsDieTest().
Member Function Documentation
breed()
bool Ant::breed (Grid * grid) [virtual]
Creates another Ant object. If an Ant survives three time steps, it will reproduce and create another Ant in an adjacent cell. If no adjacent cells are available, the Ant will wait until the next available turn to create another ant. If multiple adjacent cells are available, the Ant will choose at random which adjacent cell it will create another Ant.
Returns
whether or not the Ant was created successfully
Implements Organism .
References Ant(), Organism::c, Organism::canMoveHere(), Organism::movesWithoutBreeding, Grid::numAnts, Organism::r, and Grid::setCellOccupant().
Referenced by Tests2::antsBreedTest(), Tests2::antsDontBreedTest(), and step().
move()
bool Ant::move (Grid * grid) [virtual]
Moves the Ant to a nearby cell. If the Ant is surrounded by available adjacent cells (above, below, or to the left or right of the ant), it will move to one of these at random. If no cells are available, the Ant will remain in the same location.
Returns
Whether the Ant moved successfully
Implements Organism .
References Organism::c, Organism::canMoveHere(), Organism::movesWithoutBreeding, Organism::r, and Grid::setCellOccupant().
Referenced by Tests2::antsDontMoveTest(), Tests2::antsMoveTest(), Tests2::doodleEatTest(), and step().
step()
void Ant::step (Grid * grid) [virtual]
Causes the Ant to take a step, i.e. move and/or breed
Implements Organism .
References breed(), move(), and Organism::movesWithoutBreeding.
The documentation for this class was generated from the following files:
 Ant.h
 Ant.cpp